version: "3.7"
services:
  nginx:
    build:
      context:    ..
      dockerfile: ./infra/nginx/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ../site/public:/srv/app/public
  php:
    build:
      context: ..
      dockerfile: ./infra/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    restart: unless-stopped
    healthcheck:
      interval:     10s
      timeout:      3s
      retries:      3
      start_period: 30s
    volumes:
      - ../site:/srv/app:cached
      - ../site/var:/srv/app/var:delegated
