sonata_media:
  default_context: default
  contexts:
    default:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file

      formats:
        small: { width: 100 , quality: 70 }
        big: { width: 500 , quality: 70 }

  cdn:
    server:
      path: 'https://awsdemos3.s3-accelerate.amazonaws.com'

  providers:
    image:
      filesystem: sonata.media.filesystem.s3
    file:
      filesystem: sonata.media.filesystem.s3

  filesystem:
    s3:
      bucket:    '%env(string:S3_BUCKET)%'
      accessKey: '%env(string:AWS_ACCESS_KEY)%'
      secretKey: '%env(string:AWS_SECRET_KEY)%'
      region:    '%env(string:S3_REGION)%'
      version:   '%env(string:S3_VERSION)%'

  adapters:
    default: 'sonata.media.adapter.image.imagick'
