sonata_media:
  default_context: default
  contexts:
    default:
      providers:
        - sonata.media.provider.image
        - sonata.media.provider.file

      formats:
        small: { width: 100 , quality: 70 }
        big: { width: 500 , quality: 70 }

  cdn:
    server:
      path: https://awsdemos3.s3-accelerate.amazonaws.com

  providers:
    image:
      filesystem: sonata.media.filesystem.s3

  filesystem:
    s3:
      bucket:    '%env(S3_BUCKET)%'
      accessKey: '%env(AWS_ACCESS_KEY)%'
      secretKey: '%env(AWS_SECRET_KEY)%'
      region:    '%env(S3_REGION)'
      version:   '%env(S3_VERSION)%'
      endpoint:  '%env(S3_ENDPOINT)%'

  adapters:
    default: 'sonata.media.adapter.image.imagick'
